[graph]
targets = [
  "x86_64-unknown-linux-gnu",
  "wasm32-unknown-unknown",
  "aarch64-linux-android",
  "aarch64-apple-ios",
]
all-features = false

[advisories]
version = 2
ignore = []

[licenses]
version = 2
allow = [
  "MIT", "Apache-2.0", "Apache-2.0 WITH LLVM-exception", "BSD-2-Clause", "BSD-3-Clause",
  "ISC", "Zlib", "Unicode-3.0", "Unicode-DFS-2016", "MPL-2.0", "CC0-1.0", "OFL-1.1",
  "BSL-1.0", "Unlicense", "0BSD", "CDLA-Permissive-2.0", "CC-BY-NC-SA-4.0",
  "Ubuntu-font-1.0", # egui default fonts
]
confidence-threshold = 0.9

[bans]
multiple-versions = "warn"
wildcards = "deny"
allow-wildcard-paths = true

[sources]
unknown-registry = "deny"
unknown-git = "deny"
